main:
  vscode:
    - docker:
        image: docker.cnb.cool/liyao52033/images/debian:latest
      runner:
        cpus: 16
      services:
        - vscode
        - docker
      stages:
        - name: 默认安装依赖
          script: |
            ls -al

  push:
    - services:
        - docker
      stages:
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/liyao52033/envs/-/blob/main/github-env.yml
          script:
          # 强制推送本地main分支到远程target（GitHub）的main分支，覆盖远程所有历史
          - git push target main --force
          settings:
            target_url: https://github.com/liyao52033668/CLIProxyAPIPlus.git
            auth_type: https
            git_user: ${GIT_USERNAME_NEW}
            git_email: ${GIT_EMAIL_NEW}
            username: ${GIT_USERNAME_NEW}
            password: ${GIT_ACCESS_TOKEN_NEW}