host: '127.0.0.1'
port: 18317
remote-management:
  allow-remote: false
  secret-key: 'testkey'
  disable-control-panel: false
auth-dir: '/mnt/d/AAWebProjects/15.go/cpa/CLIProxyAPIPlus/auths'
usage-statistics-enabled: false
