package registry

// FreebuffCatalogEntry is one upstream Freebuff (Codebuff) model together with
// the root agent the run executes under.
//
// Agent ids track the current base3 harness; LegacyAgentID carries the base2
// rollback id so a config can pin the older harness explicitly.
type FreebuffCatalogEntry struct {
	// ID is the upstream wire model id passed to chat/completions.
	ID string
	// DisplayName is the name upstream shows in its picker.
	DisplayName string
	// AgentID is the base3 root agent id for this model.
	AgentID string
	// LegacyAgentID is the base2 root agent id, kept for rollback.
	LegacyAgentID string
	// InPicker reports whether upstream's client picker still offers this model.
	// Models accepted by the server but not offered are still listed so they can
	// be configured deliberately.
	InPicker bool
	// ContextLength is the advertised context window.
	ContextLength int
	// Thinking describes the model's reasoning support, or nil when unsupported.
	Thinking *ThinkingSupport
}

// freebuffCatalog is the Freebuff (Codebuff) model directory. It is generated by
// cmd/sync_freebuff_catalog from the upstream TypeScript catalog; see
// freebuff_catalog_generated.go for the entries and their provenance.
//
// Upstream serves no model-list endpoint, so this catalog is compiled in and is
// the single source of truth for both the model directory and the runtime
// fallback table. The first entry is upstream's default model, so a bare
// "freebuff"/"codebuff" request resolves to it.

// GetFreebuffCatalog returns the Freebuff model/agent catalog.
// The returned slice is shared; callers must not modify it.
func GetFreebuffCatalog() []FreebuffCatalogEntry {
	return freebuffCatalog
}

// GetFreebuffModels returns the Freebuff (Codebuff) catalog as model metadata,
// used for model listing and alias configuration.
func GetFreebuffModels() []*ModelInfo {
	out := make([]*ModelInfo, 0, len(freebuffCatalog))
	for _, entry := range freebuffCatalog {
		out = append(out, &ModelInfo{
			ID:            entry.ID,
			Object:        "model",
			OwnedBy:       "freebuff",
			Type:          "freebuff",
			DisplayName:   entry.DisplayName,
			Description:   entry.AgentID,
			ContextLength: entry.ContextLength,
			Thinking:      entry.Thinking,
		})
	}
	return out
}
