// Code generated by cmd/sync_freebuff_catalog. DO NOT EDIT.
//
// Upstream exposes no model-list endpoint, so this catalog is generated by
// parsing the upstream TypeScript catalog and model -> root agent maps.
//
// Source: CodebuffAI/codebuff@main
//   - common/src/constants/freebuff-models.ts (default model, picker order, context windows, reasoning ladders)
//   - common/src/constants/free-agents.ts     (model -> base3 root agent, base2 rollback roots)
//
// Regenerate with:
//
//	go run ./cmd/sync_freebuff_catalog -write
package registry

// freebuffCatalog is the Freebuff (Codebuff) model directory. The first entry
// is upstream's default model; a bare "freebuff"/"codebuff" request resolves to it.
var freebuffCatalog = []FreebuffCatalogEntry{
	{
		ID:            "z-ai/glm-5.3-flash",
		DisplayName:   "GLM 5.3 Flash",
		AgentID:       "base3-free-glm-5-3-flash",
		LegacyAgentID: "base2-free-glm-5-3-flash",
		InPicker:      true,
		ContextLength: 1000000,
		Thinking:      &ThinkingSupport{Levels: []string{"low", "high", "max"}},
	},
	{
		ID:            "deepseek/deepseek-v4-flash",
		DisplayName:   "DeepSeek V4.1 Flash",
		AgentID:       "base3-free-deepseek-flash",
		LegacyAgentID: "base2-free-deepseek-flash",
		InPicker:      true,
		ContextLength: 1048576,
		Thinking:      &ThinkingSupport{Levels: []string{"low", "high", "max"}},
	},
	{
		ID:            "openai/gpt-5.6-luna",
		DisplayName:   "GPT-5.6 Luna",
		AgentID:       "base3-free-luna",
		LegacyAgentID: "base2-free-luna",
		InPicker:      true,
		ContextLength: 1000000,
		Thinking:      &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh", "max"}},
	},
	{
		ID:            "mimo/mimo-v2.5",
		DisplayName:   "MiMo 2.5",
		AgentID:       "base3-free-mimo",
		LegacyAgentID: "base2-free-mimo",
		InPicker:      true,
		ContextLength: 131072,
	},
	{
		ID:            "upstage/solar-pro4",
		DisplayName:   "Solar Pro 4",
		AgentID:       "base3-free-solar-pro4",
		LegacyAgentID: "base2-free-solar-pro4",
		InPicker:      true,
		ContextLength: 500000,
	},
	{
		ID:            "meta/muse-spark-1.2-contributor",
		DisplayName:   "Muse Spark 1.2",
		AgentID:       "base3-free-muse-spark",
		LegacyAgentID: "base2-free-muse-spark",
		InPicker:      true,
		ContextLength: 1000000,
		Thinking:      &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh"}},
	},
	{
		ID:            "anthropic/claude-fable-5",
		DisplayName:   "Claude Fable 5",
		AgentID:       "base3-free-fable",
		LegacyAgentID: "base2-free-fable",
		ContextLength: 131072,
		Thinking:      &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh", "max"}},
	},
	{
		ID:            "google/gemini-3.8-flash",
		DisplayName:   "Gemini 3.8 Flash",
		AgentID:       "base3-free-gemini-3-8-flash",
		LegacyAgentID: "base2-free-gemini-3-8-flash",
		ContextLength: 131072,
		Thinking:      &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh", "max"}},
	},
	{
		ID:            "openai/gpt-5.6-luna-es",
		DisplayName:   "Codex (test)",
		AgentID:       "base3-free-luna-es",
		LegacyAgentID: "base2-free-luna-es",
		ContextLength: 372000,
	},
	{
		ID:            "crof/kimi-k3-eco",
		DisplayName:   "Kimi K3",
		AgentID:       "base3-free-kimi-k3-eco",
		LegacyAgentID: "base2-free-kimi-k3-eco",
		ContextLength: 131072,
	},
}
