// Package registry provides model definitions for various AI service providers.
package registry

// GetMetaModels returns the static Meta (Muse Code) fallback catalog.
func GetMetaModels() []*ModelInfo {
	return []*ModelInfo{
		{
			ID:                        "muse-spark-1.3",
			Object:                    "model",
			Created:                   1787000000,
			OwnedBy:                   "meta",
			Type:                      "meta",
			DisplayName:               "Muse Spark 1.3",
			Name:                      "muse-spark-1.3",
			Description:               "Meta Muse Spark 1.3 flagship reasoning and agentic coding model",
			ContextLength:             1048576,
			MaxCompletionTokens:       65536,
			Thinking:                  &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh", "max"}},
			SupportedInputModalities:  []string{"text", "image"},
			SupportedOutputModalities: []string{"text"},
		},
		{
			ID:                        "muse-spark-1.3-contributor",
			Object:                    "model",
			Created:                   1787000000,
			OwnedBy:                   "meta",
			Type:                      "meta",
			DisplayName:               "Muse Spark 1.3 Contributor",
			Name:                      "muse-spark-1.3-contributor",
			Description:               "Meta Muse Spark 1.3 contributor model",
			ContextLength:             1048576,
			MaxCompletionTokens:       65536,
			Thinking:                  &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh", "max"}},
			SupportedInputModalities:  []string{"text", "image"},
			SupportedOutputModalities: []string{"text"},
		},
		{
			ID:                        "muse-spark-1.2",
			Object:                    "model",
			Created:                   1785000000,
			OwnedBy:                   "meta",
			Type:                      "meta",
			DisplayName:               "Muse Spark 1.2",
			Name:                      "muse-spark-1.2",
			Description:               "Meta Muse Spark 1.2 reasoning and agentic coding model",
			ContextLength:             1048576,
			MaxCompletionTokens:       65536,
			Thinking:                  &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh"}},
			SupportedInputModalities:  []string{"text", "image"},
			SupportedOutputModalities: []string{"text"},
		},
		{
			ID:                        "muse-spark-1.2-contributor",
			Object:                    "model",
			Created:                   1785000000,
			OwnedBy:                   "meta",
			Type:                      "meta",
			DisplayName:               "Muse Spark 1.2 Contributor",
			Name:                      "muse-spark-1.2-contributor",
			Description:               "Meta Muse Spark 1.2 contributor model",
			ContextLength:             1048576,
			MaxCompletionTokens:       65536,
			Thinking:                  &ThinkingSupport{Levels: []string{"minimal", "low", "medium", "high", "xhigh"}},
			SupportedInputModalities:  []string{"text", "image"},
			SupportedOutputModalities: []string{"text"},
		},
		{
			ID:                        "muse-spark-1.1",
			Object:                    "model",
			Created:                   1783000000,
			OwnedBy:                   "meta",
			Type:                      "meta",
			DisplayName:               "Muse Spark 1.1",
			Name:                      "muse-spark-1.1",
			Description:               "Meta Muse Spark 1.1 reasoning model",
			ContextLength:             1048576,
			MaxCompletionTokens:       65536,
			Thinking:                  &ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}},
			SupportedInputModalities:  []string{"text"},
			SupportedOutputModalities: []string{"text"},
		},
	}
}
