name: Sync to HuggingFace

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0   

      - name: Remove binary files before push
        run: |
          rm -rf assets/*.png
          rm -rf asset/ad/*.png
          git rm -r --cached assets/*.png || true
          git rm -r --cached asset/ad/*.png || true
          git config user.name "hf-bot"
          git config user.email "bot@users.noreply.github.com"
          git commit -m "clean binary for hf push" || true

      - name: Setup Git LFS
        run: |
          git lfs install

      - name: Push to HF
        run: |
          git remote add hf https://lliyao52033:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/liyao52033/cpa
          git push hf main --force
