name: Sync to HuggingFace

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0   


      - name: Clean git history
        run: |
          pip install git-filter-repo
          git filter-repo \
            --path assets/lingtrue.png \
            --path asset/ad/chinese.png \
            --path asset/ad/english.png \
            --invert-paths

      - name: Setup Git LFS
        run: |
          git lfs install

      - name: Push to HF
        run: |
          git remote add hf https://lliyao52033:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/liyao52033/cpa
          git push hf main --force
